---
name: "idx"
fs:
  indexed_chars: 100%
  lang_detect: true
  continue_on_error: true
  ocr:
    language: "eng+mya"
    enabled: true
    pdf_strategy: "auto"
    # pdf_strategy: "ocr_and_text"
elasticsearch:
  index: "documents"
  nodes:
    - url: "http://elasticsearch:9200"
      ssl:
        certificate_verification: false
  # username: "elastic"
  # password: "changeme"
  # ssl_verification: false
rest :
  url: "http://fscrawler:8080"

